using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;

namespace WpfFarseer
{
    public class BasicControl : DependencyObject
    {
        //protected
        public Canvas _canvas = new Canvas();
        static int i = 0;
        private string _generateName()
        {
            return string.Format("autogenerated_{0}", i++);
        }
        public BasicControl()
        {
            Id = _generateName();
        }

        public string Id { get; set; }

    }
}
