using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;

namespace SM.Wpf
{
    public class BasicControl : DependencyObject
    {
        protected Canvas _canvas = new Canvas();
        private Panel _parent;
        public void RegisterTo(Panel parent)
        {
            _parent = parent;
            _parent.Children.Add(_canvas);
        }
        static int i = 0;
        private string _generateName()
        {
            return string.Format("autogenerated_{0}", i++);
        }
        public BasicControl()
        {
            Id = _generateName();
        }

        public string Id { get; set; }

    }
}
