using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;

namespace SM.Wpf
{
    // controlli in grado di agganciare il proprio canvas al canvas padre
    public class BasicControl : DependencyObject
    {
        protected Canvas _canvas = new Canvas();
        protected Canvas _parent;
        public void RegisterToParent(Canvas parent)
        {
            _parent = parent;
            _parent.Children.Add(_canvas);
        }
        static int i = 0;
        public static string AutoGenerateName()
        {
            return string.Format("autogenerated_{0}", i++);
        }
        public BasicControl()
        {
            if (Id == null || Id == "")
            {
                Id = BasicControl.AutoGenerateName();
            }
        }

        public string Id
        {
            get;
            set;
        }

    }
}
