using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Controls;

namespace SM.WpfView
{
    public class CanvasId : Canvas
    {
        static int i = 0;
        private static string GetAutoGenerateName()
        {
            return string.Format("autogenerated_{0}", i++);
        }

        public CanvasId()
        {
            Id = GetAutoGenerateName();
        }

        public string Id { get; set; }
    }
}
